[project]
name = "project-northstar"
version = "0.1.0"
description = "AI-driven triage and knowledge generation system (hackathon scaffold)"
authors = [ { name = "Team NorthStar" } ]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.dependencies]
google-cloud-bigquery = ">=3.25.0"

[project.urls]
Homepage = "https://example.com/project-northstar"

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff", "mypy", "types-requests"]

[tool.ruff]
line-length = 79
select = ["E", "F", "I", "UP", "B", "SIM", "S", "N"]
ignore = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-q"

[tool.mypy]
python_version = "3.12"
strict = true
packages = ["core", "."]
ignore_missing_imports = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
