name: Secret Scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -e .[dev]
      - name: Run secret sweep (medium threshold)
        run: python scripts/secret_sweep.py --fail-on medium --allowlist secrets_allowlist.txt --json > secret-scan.json || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: secret-scan
            path: secret-scan.json
      - name: Summarize
        run: |
          echo "### Secret Scan" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat secret-scan.json || true >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
